# @package _global_

#defaults:
#  - environment/base


model:
    n_hidden : 3
    hidden_size : 32 # NOTE: Perhaps replace with an array describing layers?
    batch_norm : False # NOTE: Can't be True if batch_size==1. We may add an assertion for this
    activation : 'ReLU'

data: # (does it need to be nested?)
    sites : ["CH-Dav"] 
    #site_name = ["DE-Tha"]
    #site_name = ["DE-Hai"]
    #site_name = ["US-Me2"]
    base_path : "~/epfl/semester_project/databases/T_C_PIPELINE_DATA/"
    nPoints : 1000 # -> decide if we want to truncate, what to do in training?
    # perhaps options on what to filter? do we filter negative Q_LE? stuff like that

pipeline:
    # modelMapping : 'softplus'
    # which pipeline?
    use_vmax : False

train:
    #lr: [1e-1, 1e-2, 1e-3]
    lr: 1e-2
    epochs: 10000
    #weight_decay: [1e-2, 1e-4, 1e-6, 0]
    weight_decay: 1e-6
    batch_size: 1
    hp_tuning: False # If this is true, hyperparameters are expected to be arrays.
    # loss?opt?iterator?


wandb:
  use_wandb: False
  project: "change-project"
  tags: ['default_config']

#hydra:
#  job:
#    chdir: True
#  run:
#    dir: ./outputs/${environment.gym_name}/${now:%Y-%m-%d}/${now:%H-%M-%S}
#  sweeper:
#    params:
#      +sweep_id: ${generate_random_seed:}