"""
In this experiment, we use only wet sites for training.
"""

model:
    n_hidden : 4
    hidden_size : 64 # NOTE: Perhaps replace with an array describing layers?
    batch_norm : True # NOTE: Can't be True if batch_size==1. We may add an assertion for this
    activation : 'ReLU'

data: # (does it need to be nested?)
    sites : ["CH-Dav", "AR-Vir", "AU-Ade", "AU-Stp"] 
    base_path : "~/epfl/semester_project/databases/T_C_PIPELINE_DATA/"
    nPoints : 500 # -> decide if we want to truncate, what to do in training?
    exclude_negative : False

pipeline:
    use_vmax : False
    predict_rs: True # If false, we predict gsCO2 instead, and perform physical operations to obtain rs.

train:
    lr: 1e-3
    epochs: 1000
    weight_decay: 1e-4
    batch_size: 100
    test_split: 0.2
    hp_tuning: False # If this is true, hyperparameters are expected to be arrays.

wandb:
  use_wandb: False
  project: "change-project"
  tags: ['default_config']

model_weights_path: "model_weights/default_model.pt"